In [ ]:
from sklearn.preprocessing import LabelEncoder

harga = ['Murah', 'Medium', 'Mahal']

encoder = LabelEncoder()
encoded_gender = encoder.fit_transform(harga)

print(encoded_gender)


[2 1 0]


In [15]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

genre = np.array(['Horror natural', 'Horror', 'Thriller', 'Mystery', 'Comedy']).reshape(-1, 1)

encoder = OneHotEncoder()
encoded_status = encoder.fit_transform(genre).toarray()

print(encoded_status)


[[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

texts = ["Ini adalah contoh teks", "Teks lainnya untuk analisis"]

vectorizer = TfidfVectorizer()
encoded_texts = vectorizer.fit_transform(texts)

print(encoded_texts.toarray())


[[0.53404633 0.         0.53404633 0.53404633 0.         0.37997836
  0.        ]
 [0.         0.53404633 0.         0.         0.53404633 0.37997836
  0.53404633]]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

texts = [
    "Saya suka belajar machine learning",
    "Belajar machine learning itu menyenangkan",
    "Saya juga suka belajar data science"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(texts)

print("Fitur (kata unik):")
print(vectorizer.get_feature_names_out())

print("\nMatriks Bag of Words:")
print(X.toarray())


Fitur (kata unik):
['belajar' 'data' 'itu' 'juga' 'learning' 'machine' 'menyenangkan' 'saya'
 'science' 'suka']

Matriks Bag of Words:
[[1 0 0 0 1 1 0 1 0 1]
 [1 0 1 0 1 1 1 0 0 0]
 [1 1 0 1 0 0 0 1 1 1]]
